services:
  webassets:
    build: .
    ports:
      - "80:80"
    depends_on:
      - dbassets
    environment:
      - DATABASE_URL=postgresql://postgres:password@dbassets:5432/postgres
  dbassets:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
